project:
  type: website

website:
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: intro_mixed.qmd
        text: Introduction
      - href: curation.qmd
        text: Curation
      - href: analysis_1.qmd
        text: Analysis
      - href: results.qmd
        text: Results
      - href: extension.qmd
        text: Extension
    right:
      - icon: github
        href: https://github.com/ImperialCollegeLondon/The-Random-Side-A-Mixed-Model-Adventure/tree/main  # include your GitHub repo URL
        aria-label: GitHub

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    