project:
  type: website

website:
  title: "ReCoDE: Mixed models R tutorial"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: intro_mixed.qmd
        text: Introduction
    right:
      - icon: github
        href: https://github.com/ImperialCollegeLondon/ReCoDE-exemplar-template-R   # include your GitHub repo URL
        aria-label: GitHub

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



